[
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
      geo: {
        lat: "-37.3159",
        lng: "81.1496",
      },
    },
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
    company: {
      name: "Romaguera-Crona",
      catchPhrase: "Multi-layered client-server neural-net",
      bs: "harness real-time e-markets",
    },
  },

  {
    id: 1,
    name: "Monte Cristo Sandwich",
    foto: {
      1: "/1.1.jpg",
      2: "/1.2.jpg",
      3: "/1.3.jpg",
    },
    description:
      " slices bread, honey dijon mustard, slices thin deli sliced swiss cheese, slices thin deli ham, slices thin deli sliced turkey, eggs,  milk ",
    price: "25",
    category: "Breakfast",
  },
  {
    id: 2,
    name: "Pasteles De Guayaba",
    foto: {
      1: "/2.1.jpg",
      2: "/2.2.jpg",
      3: "/2.3.jpg",
    },
    description: "cream cheese,  butter (softened), flour, guava paste, sugar",
    price: "15",
    category: "Breakfast",
  },
  {
    id: 3,
    name: "Italian Breakfast Wraps",
    foto: {
      1: "/3.1.jpg",
      2: "/3.2.jpg",
      3: "/3.3.jpg",
    },
    description:
      "whole wheat tortillas, fat free mozzarella cheese, olive oil, garlic clove,  fresh mushrooms, zucchini, green pepper,  shallot, grape tomatoes, slice turkey bacon, italian seasoning",
    price: "20",
    category: "Breakfast",
  },
  {
    id: 4,
    name: "Irish Breakfast",
    foto: {
      1: "/4.1.jpg",
      2: "/4.2.jpg",
      3: "/4.3.jpg",
    },
    description:
      "pork sausage, slices lean bacon, thickly sliced disks of clonakilty white pudding sausage, disks of clonakilty blood pudding sausage, button mushrooms, eggs, kerrygold real irish butter, irish brown bread, Heinz ketchup, freshly squeezed orange juice  ",
    price: "35",
    category: "Breakfast",
  },
  {
    id: 5,
    name: "OLD FASHIONED ENGLISH BREAKFAST",
    foto: {
      1: "/5.1.jpg",
      2: "/5.2.jpg",
      3: "/5.3.jpg",
    },
    description:
      "pork, fine dry breadcrumb, white pepper, ground ginger, ground sage, thyme leaves, ground allspice",
    price: "32",
    category: "Breakfast",
  },
  {
    id: 6,
    name: "PUFFY FRENCH TOAST",
    foto: {
      1: "/6.1.jpg",
      2: "/6.2.jpg",
      3: "/6.3.jpg",
    },
    description:
      "slices white bread, beaten egg, nutmeg, cinnamon, milk, flour",
    price: "22",
    category: "Breakfast",
  },
  {
    id: 7,
    name: "PEPPERONI PASTA SALAD",
    foto: {
      1: "/7.1.jpg",
      2: "/7.2.jpg",
      3: "/7.3.jpg",
    },
    description:
      "bow tie pasta, pepperoni, Italian salad dressing, grated parmesan cheese, italian seasoning",
    price: "18",
    category: "Lunch",
  },
  {
    id: 8,
    name: "LEMONY WALDORF FISH FILLETS",
    foto: {
      1: "/8.1.jpg",
      2: "/8.2.jpg",
      3: "/8.3.jpg",
    },
    description:
      "apple, celery, butter, herb seasoned stuffing mix, salad dressing, walnuts, lemon juice, fish fillet",
    price: "24",
    category: "Lunch",
  },
  {
    id: 9,
    name: "CHEESY TURKEY BURGER",
    foto: {
      1: "/9.1.jpg",
      2: "/9.2.jpg",
      3: "/9.3.jpg",
    },
    description:
      "ground turkey, garlic powder, onion powder, celery seed, oregano, Worcestershire sauce, breadcrumbs, shredded cheddar cheese, pepper ",
    price: "25",
    category: "Lunch",
  },
  {
    id: 10,
    name: "CLASSIC BLT SANDWICH",
    foto: {
      1: "/10.1.jpg",
      2: "/10.2.jpg",
      3: "/10.3.jpg",
    },
    description:
      "bacon, slices white bread, leaves iceberg lettuce, slices of ripened tomatoes, Hellmann's mayonnaise",
    price: "20",
    category: "Lunch",
  },
  {
    id: 11,
    name: "HEALTHY EGG SALAD SANDWICH",
    foto: {
      1: "/11.1.jpg",
      2: "/11.2.jpg",
      3: "/11.3.jpg",
    },
    description:
      "hard-boiled eggs, chopped scallions, Dijon mustard, pieces lettuce, slices whole grain bread, salt and pepper ",
    price: "15",
    category: "Lunch",
  },
  {
    id: 12,
    name: "SALMON FILLETS",
    foto: {
      1: "/12.1.jpg",
      2: "/12.2.jpg",
      3: "/12.3.jpg",
    },
    description: "salmon fillets, lemon pepper seasoning, butter, rice",
    price: "30",
    category: "Lunch",
  },
  {
    id: 13,
    name: "GOAT CHEESE GOURMET PIZZA",
    foto: {
      1: "/13.1.jpg",
      2: "/13.2.jpg",
      3: "/13.3.jpg",
    },
    description: "pizza dough, olive oil, small sweet onion, fresh figs, ounces goat cheese, chopped fresh rosemary, mozzarella cheese,cornmeal",
    price: "25",
    category: "Pizza",
  },
  {
    id: 14,
    name: "GOURMET PESTO PIZZA",
    foto: {
      1: "/14.1.jpg",
      2: "/14.2.jpg",
      3: "/14.3.jpg",
    },
    description: "whole wheat pizza dough, olive oil, sliced mushrooms, small onion, herbed goat cheese, shredded part-skim mozzarella cheese, black olives, pesto sauce",
    price: "22",
    category: "Pizza",
  },
  {
    id: 15,
    name: "DOUBLE CHEESE PITA PIZZAS",
    foto: {
      1: "/15.1.jpg",
      2: "/15.2.jpg",
      3: "/15.3.jpg",
    },
    description: "extra-virgin olive oil, Italian turkey sausage, garlic cloves, leaf spinach, 2% percent cottage cheese, whole wheat pita bread, thinly sliced red onion, ounces shredded part-skim mozzarella cheese, fresh basil leaf",
    price: "25",
    category: "Pizza",
  },
  {
    id: 16,
    name: "GOURMET CRUISERS' VEGETARIAN PIZZA",
    foto: {
      1: "/16.1.jpg",
      2: "/16.2.jpg",
      3: "/16.3.jpg",
    },
    description: "pizza dough, tomato paste, garlic cloves, mozzarella cheese, cups spinach leaves, mushroom, tomatoes, broccoli floret, bell pepper, onion, black olives, sun-dried tomato, italian seasoning, salt and pepper",
    price: "30",
    category: "Pizza",
  },
  {
    id: 17,
    name: "FOUR CHEESE WHITE BROCCOLI PIZZA",
    foto: {
      1: "/17.1.jpg",
      2: "/17.2.jpg",
      3: "/17.3.jpg",
    },
    description: "extra virgin olive oil, pizza dough, grated parmesan cheese, provolone cheese, broccoli florets, ricotta cheese, mozzarella cheese, garlic powder oregano",
    price: "25",
    category: "Pizza",
  },
  {
    id: 18,
    name: "COCONUT SHRIMP PIZZA",
    foto: {
      1: "/18.1.jpg",
      2: "/18.2.jpg",
      3: "/18.3.jpg",
    },
    description: "pizza dough, butter, garlic cloves, panko breadcrumbs, sweetened flaked coconut, eggs, small shrimp, canola oil, shredded mozzarella cheese, red fresno chile, diced pineapple, red onion, chopped scallions, kosher salt ground black pepper",
    price: "35",
    category: "Pizza",
  },
  {
    id: 19,
    name: "BEST EVER LASAGNA",
    foto: {
      1: "/19.1.jpg",
      2: "/19.2.jpg",
      3: "/19.3.jpg",
    },
    description: "lean ground beef, Italian sausage, onion, garlic, fresh coarse ground black pepper, dried parsley flakes, dried oregano, dried basil, whole tomatoes, tomato paste, ricotta cheese, eggs, grated parmesan cheese, mozzarella cheese",
    price: "20",
    category: "Dinner",
  },
  {
    id: 20,
    name: "GROUND BEEF GYROS",
    foto: {
      1: "/20.1.jpg",
      2: "/20.2.jpg",
      3: "/20.3.jpg",
    },
    description: "plain yogurt, chopped seeded cucumber, chopped onions, garlic clove, sugar, lean ground beef, dried oregano, garlic powder, onion powder, pita breads, shredded lettuce, large tomatoes, onion",
    price: "32",
    category: "Dinner",
  },
  {
    id: 21,
    name: "JAPANESE MUM'S CHICKEN",
    foto: {
      1: "/21.1.jpg",
      2: "/21.2.jpg",
      3: "/21.3.jpg",
    },
    description: "chicken drumsticks, balsamic vinegar, soy sauce, sugar, garlic clove, hot chili pepper",
    price: "35",
    category: "Dinner",
  },
  {
    id: 22,
    name: "LEMON BAKED COD",
    foto: {
      1: "/22.1.jpg",
      2: "/22.2.jpg",
      3: "/22.3.jpg",
    },
    description: "cod fish fillet, butter or 1/4 cup margarine, lemon juice, all-purpose flour, salt, white pepper, paprika",
    price: "27",
    category: "Dinner",
  },
  {
    id: 23,
    name: "BARBECUE RIBS",
    foto: {
      1: "/23.1.jpg",
      2: "/23.2.jpg",
      3: "/23.3.jpg",
    },
    description: "pork ribs, light brown sugar, hickory smoke salt, paprika, garlic, ground red pepper, your favorite barbecue sauce",
    price: "37",
    category: "Dinner",
  },
  {
    id: 24,
    name: "TRADITIONAL IRISH SHEPHERD'S PIE",
    foto: {
      1: "/24.1.jpg",
      2: "/24.2.jpg",
      3: "/24.3.jpg",
    },
    description: "olive oil, black pepper,ground beef, onion, carrots,peas, fresh thyme, butter, red wine, tomato paste, Worcestershire sauce, mashed potatoes, egg, parmesan cheese",
    price: "36",
    category: "Dinner",
  },
  {
    id: 25,
    name: "HOMEMADE YELLOW CAKE",
    foto: {
      1: "/25.1.jpg",
      2: "/25.2.jpg",
      3: "/25.3.jpg",
    },
    description: "cake flour, baking powder, salt, sugar, instant vanilla pudding, butter, milk, vanilla extract, sour cream, eggs",
    price: "40",
    category: "Dessert",
  },
  {
    id: 26,
    name: "BOSTON CREAM PIE",
    foto: {
      1: "/26.1.jpg",
      2: "/26.2.jpg",
      3: "/26.3.jpg",
    },
    description: "eggs, cake flour, sugar, baking powder, vegetable oil, milk, vanilla extract, milk chocolate",
    price: "35",
    category: "Dessert",
  },
  {
    id: 27,
    name: "CHOCOLATE PEANUT BUTTER PIE",
    foto: {
      1: "/27.1.jpg",
      2: "/27.2.jpg",
      3: "/27.3.jpg",
    },
    description: "chocolate chips, soft silken tofu, creamy peanut butter, sugar, vanilla, graham cracker crust",
    price: "33",
    category: "Dessert",
  },
  {
    id: 28,
    name: "FRESH PEACH TURNOVERS",
    foto: {
      1: "/28.1.jpg",
      2: "/28.2.jpg",
      3: "/28.3.jpg",
    },
    description: "sugar, cornstarch, fresh peaches, butter, cinnamon, nutmeg, puff pastry, egg, powdered sugar",
    price: "26",
    category: "Dessert",
  },
  {
    id: 29,
    name: "PEANUT-BUTTER-LOVER COOKIES",
    foto: {
      1: "/29.1.jpg",
      2: "/29.2.jpg",
      3: "/29.3.jpg",
    },
    description: "peanut butter, sugar, egg",
    price: "22",
    category: "Dessert",
  },
  {
    id: 30,
    name: "ALESSI'S TIRAMISU",
    foto: {
      1: "/30.1.jpg",
      2: "/30.2.jpg",
      3: "/30.3.jpg",
    },
    description: "egg yolks, sugar, marsala, whipping cream, sugar, mascarpone cheese, strong coffee, brandy, vanilla, Savoiardi cookies, cocoa, chocolate curls",
    price: "28",
    category: "Dessert",
  },
  {
    id: 36,
    name: "WATERMELON HERB COOLER",
    foto: {
      1: "/36.1.jpg",
      2: "/36.2.jpg",
      3: "/36.3.jpg",
    },
    description: "tequila, watermelon, mint, basil, limes, sugar, orange juice, ice",
    price: "6",
    category: "Cold drinks",
  },
  {
    id: 32,
    name: "ORANGE DREAMSICKLE HEAVEN",
    foto: {
      1: "/32.1.jpg",
      2: "/32.2.jpg",
      3: "/32.3.jpg",
    },
    description: "Tang orange crystals, sweet milk, pinnacle whipped cream vodka, ice, orange slice",
    price: "4",
    category: "Cold drinks",
  },
  {
    id: 33,
    name: "MANGO SANGRIA",
    foto: {
      1: "/33.1.jpg",
      2: "/33.2.jpg",
      3: "/33.3.jpg",
    },
    description: "mango juice, orange juice, merlot, seltzer water, lime slices, lemon slices",
    price: "7",
    category: "Cold drinks",
  },
  {
    id: 34,
    name: "SANGRIA SLUSH",
    foto: {
      1: "/34.1.jpg",
      2: "/34.2.jpg",
      3: "/34.3.jpg",
    },
    description: "crushed pineapple, dry red wine, orange juice, lemon juice, sugar, lemon",
    price: "6",
    category: "Cold drinks",
  },
  {
    id: 35,
    name: "CARIBBEAN RUM OR NO RUM ZING",
    foto: {
      1: "/35.1.jpg",
      2: "/35.2.jpg",
      3: "/35.3.jpg",
    },
    description: "fresh orange juice, guava nectar, dark rum, ice, ginger ale, grenadine, nutmeg",
    price: "7",
    category: "Cold drinks",
  },
  {
    id: 31,
    name: "REFRESHING MOJITO",
    foto: {
      1: "/31.1.jpg",
      2: "/31.2.jpg",
      3: "/31.3.jpg",
    },
    description: "limes, leaves of fresh mint, sugar, white rum, club soda",
    price: "6",
    category: "Cold drinks",
  },
  {
    id: 37,
    name: "",
    foto: {
      1: "/37.1.jpg",
      2: "/37.2.jpg",
      3: "/37.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 38,
    name: "",
    foto: {
      1: "/38.1.jpg",
      2: "/38.2.jpg",
      3: "/38.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 39,
    name: "",
    foto: {
      1: "/39.1.jpg",
      2: "/39.2.jpg",
      3: "/39.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 40,
    name: "",
    foto: {
      1: "/40.1.jpg",
      2: "/40.2.jpg",
      3: "/40.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 41,
    name: "",
    foto: {
      1: "/41.1.jpg",
      2: "/41.2.jpg",
      3: "/41.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 42,
    name: "",
    foto: {
      1: "/42.1.jpg",
      2: "/42.2.jpg",
      3: "/42.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 43,
    name: "",
    foto: {
      1: "/43.1.jpg",
      2: "/43.2.jpg",
      3: "/43.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 44,
    name: "",
    foto: {
      1: "/44.1.jpg",
      2: "/44.2.jpg",
      3: "/44.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 45,
    name: "",
    foto: {
      1: "/45.1.jpg",
      2: "/45.2.jpg",
      3: "/45.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 46,
    name: "",
    foto: {
      1: "/46.1.jpg",
      2: "/46.2.jpg",
      3: "/46.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 47,
    name: "",
    foto: {
      1: "/47.1.jpg",
      2: "/47.2.jpg",
      3: "/47.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 48,
    name: "",
    foto: {
      1: "/48.1.jpg",
      2: "/48.2.jpg",
      3: "/48.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 49,
    name: "",
    foto: {
      1: "/49.1.jpg",
      2: "/49.2.jpg",
      3: "/49.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 50,
    name: "",
    foto: {
      1: "/50.1.jpg",
      2: "/50.2.jpg",
      3: "/50.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 51,
    name: "",
    foto: {
      1: "/51.1.jpg",
      2: "/51.2.jpg",
      3: "/51.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 52,
    name: "",
    foto: {
      1: "/52.1.jpg",
      2: "/52.2.jpg",
      3: "/52.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 53,
    name: "",
    foto: {
      1: "/53.1.jpg",
      2: "/53.2.jpg",
      3: "/53.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 54,
    name: "",
    foto: {
      1: "/54.1.jpg",
      2: "/54.2.jpg",
      3: "/54.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 55,
    name: "",
    foto: {
      1: "/55.1.jpg",
      2: "/55.2.jpg",
      3: "/55.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 56,
    name: "",
    foto: {
      1: "/56.1.jpg",
      2: "/56.2.jpg",
      3: "/56.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 57,
    name: "",
    foto: {
      1: "/57.1.jpg",
      2: "/57.2.jpg",
      3: "/57.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
  {
    id: 58,
    name: "",
    foto: {
      1: "/58.1.jpg",
      2: "/58.2.jpg",
      3: "/58.3.jpg",
    },
    description: "",
    price: "",
    category: "",
  },
];
